---
title: "Airbnb Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r airbnb data, include = FALSE}
data(nyc_airbnb) # This is a big dataset ~ 40,000 data, we need to sample down 

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  # I am making 10 stars to become 5 stars and so on..
  select(
    borough = neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), # drop any rows that don't have any ratings.
    # we are narrowing down to only Manhattan, entire home/apt, & price range within 100-500.
    borough == "Manhattan", 
    room_type == "Entire home/apt",
    price %in% 100:500)
```

```{r}
nyc_airbnb %>% 
  mutate(
    text_label = str_c("Price: $", price)) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,  
    type = "scatter", mode = "markers",
    alpha = 0.5, text = ~text_label)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(
    y = ~price, color = ~neighbourhood,
    type = "box")
```

### Chart C

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(
    x = ~neighbourhood, y = ~n, color = ~neighbourhood,
    type = "bar")
```

